# service:
# - docker

# script:
# - sudo cat /etc/docker/daemon.json
# - sudo rm /etc/docker/daemon.json
# - sudo systemctl restart docker
# - docker run openjdk ls


# service:
# - docker

script:
- sudo ip a
- sudo cat /etc/docker/daemon.json
# - sudo rm /etc/docker/daemon.json
# - curl -I 10.40.0.200:443
# - curl -I 10.30.0.28:5000
- curl -I https://registry.travis-ci.com
# - sudo cp daemon.json /etc/docker/daemon.json
# - sudo rm -f /etc/docker/daemon.json
# - sudo systemctl restart docker
# - sudo cat /etc/docker/daemon.json
- docker run node ls
- docker run ruby ls
- docker run ruby:2.7.2 ls
- docker run ruby:2.7.1 ls
- docker run ruby:2.7.0 ls
- docker run ubuntu ls
- docker run debian ls
- docker run ubuntu:18.04 ls
- docker run ubuntu:20.04 ls

jobs:
  include:
  - rvm: 2.7.2
    name: Ruby 2.7.2
  - rvm: 2.7.1
    name: Ruby 2.7.1
  - rvm: 2.7.0
    name: Ruby 2.7.0
  - rvm: 2.6.0
    name: Ruby 2.6.0
  - rvm: 2.6.1
    name: Ruby 2.6.1
  - rvm: 2.6.2
    name: Ruby 2.6.2
  - rvm: 2.6.3
    name: Ruby 2.6.3
  - rvm: 2.6.4
    name: Ruby 2.6.4
  - rvm: 2.6.5
    name: Ruby 2.6.5
  - rvm: 2.6.6
    name: Ruby 2.6.6  
